spring:
  datasource:
    url: ENC(3chkk+LvuYxJqKjD6ly1f9brtSbkYazTWemsurxpnWLCkou4kzTRHQo7y+GSGEaB7JauoaEJEy6sbRtsVg4sfRy0SgJ3nlwPO7XNVs3wOK3Q8EL0lABAv8+ggCm3L9ViT4p9hW7oI3bSyxGTorgEHwxYNHB9rjvJRVPdMI7mBJ4K0gn+xUaNWQ==)
    username: ENC(EY2UjrJjPFCehvVShq8aOA==)
    password: ENC(L/1/2wgCwnq+qDZSYeM7bePmgZa3jchPZZp2kfAW9Bk=)
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      dialect: org.hibernate.dialect.MySQL8Dialect

logging:
  level:
    app.askresume: debug # todo 패키지 수정

# JWT Token 설정 // 개발환경 인증 편하게 하기 위해
token:
  access-token-expiration-time: 9999999999999
  refresh-token-expiration-time: 9999999999999

# Swagger 설정
swagger:
  title: "ask-resume API DOCS (로컬)"
  description: "로컬서버 API 문서입니다."

oauth:
  client-home: http://localhost:4000
  providers:
    google:
      redirect-url: http://localhost:8080/api/oauth/google/callback
    linked-in:
      redirect-url: http://localhost:8080/api/oauth/linked-in/callback

management:
  endpoint:
    web:
      exposure:
        include: "*"